name: medicare
description: Doctor Appointment App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0" #dart

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  # hexcolor: ^2.0.1
  firebase_core: ^2.3.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.7.1
  flutter_screenutil: ^5.7.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.1
  mailer: ^6.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/doctors/
    - assets/clinics/
    - assets/admin/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo-regular.ttf

